apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurioregistry-kafkasql
spec:
  configuration:
    persistence: "kafkasql"
    kafkasql:
      bootstrapServers: "kafka-cluster-kafka-bootstrap:9092"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafkasql-journal
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 3
  replicas: 3
  config:
    cleanup.policy: compact
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: apicurioregistry
spec:
  subdomain: apicurioregistry-kafkasql
  to:
    kind: Service
    name: apicurioregistry-kafkasql-service
    weight: 100
  port:
    targetPort: 8080    
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None    