apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    run: postgres
spec:
  containers:
    - name: postgres
      image: quay.io/debezium/example-postgres:2.3
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
      resources:
        limits:
          cpu: 250m
          memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    run: postgres
spec:
  ports:
    - port: 5432
  selector:
    run: postgres
